### ISSUE TITLE
Add character: <p> to font: <Drpepper>

### ISSUE THREAD

**Issue by aryantanwarr** [codewithnick/ascii-art#1013]
*Character* : <p>
*Font* : <Drpepper>

**Comment by ShubhamShakyawal** [comment]
Hi @aryantanwarr I want to contribute to this. Please assign it to me.

**Comment by Saurabhyadav0** [comment]
hey sir @aryantanwarr  please assign me this project?

**Comment by AnshumanMahato** [comment]
@ShubhamShakyawal @Saurabhyadav0look for issues with the 'up-for-grab tag and request for assignment there. Also, wait for the assignment before initiating a PR.
