### ISSUE TITLE
Add character: <m> to font: <straight>

### ISSUE THREAD

**Issue by AnshumanMahato** [codewithnick/ascii-art#1073]
*Character* : <m>
*Font* : <straight>

**Comment by MutiatBash** [comment]
Hello @AnshumanMahato 
Please can I work on this

**Comment by weshaan** [comment]
is this still on?

**Comment by AnshumanMahato** [comment]
@weshaan you want it?

**Comment by weshaan** [comment]
yes, I'll do it :)

**Comment by weshaan** [comment]
hey, its done! pls review my PR... hacktoberfest ends today so I'm kinda low on time too :_)
