### ISSUE TITLE
Fix compilation warnings

### ISSUE THREAD

**Issue by jlewismith** [codewithnick/ascii-art#1098]
There are many warnings when compiling the project. The most common source of the warning is redundant assignments in <fontname>.h files.

The redundant code generally looks like this:
```
character[0][0] = character[0][0] = '-'; // assigning the same array index multiple times
```

Code like this causes many extra printed lines of code when compiling and is easily fixed by not assigning the same array index multiple times. 

There are other warning messages too that can be fixed, but most of the problems are from these redundant assignments.

**Comment by AnshumanMahato** [comment]
@jlewismith. what compiler are you using? Mine doesn't show any warnings, so I would like to see what exactly is happening.

**Comment by jlewismith** [comment]
> @jlewismith. what compiler are you using? Mine doesn't show any warnings, so I would like to see what exactly is happening.

I'm using g++ on Windows. It looks like my VS Code setup uses the `-Wall` and `-Wextra` flags during compilation.

**Comment by codewithnick** [comment]
@AnshumanMahato looks geniune to me reassignment to the same grid piece is kind of inefficient!

**Comment by AnshumanMahato** [comment]
@codewithnick yes I get that... I just wanted to know why I ain't getting those warnings. I am going to merge this eventually.

**Comment by codewithnick** [comment]
yeah neither did I
