### ISSUE TITLE
Explicitly report the license

### ISSUE THREAD

**Issue by fcorbelli** [codewithnick/ascii-art#1111]
Please explicitly report the license to use this code
Certain Linux distributions (Debian for example) require to very carefully specify each and every license used

**Comment by codewithnick** [comment]
what do you mean? do you want us to add a license?

**Comment by fcorbelli** [comment]
Exactly. 

Being a derivative of MIT license it could be MIT itself. 

Or public domain. 
Or whatever. 
But without a license you can't use it for Debian

**Comment by fcorbelli** [comment]
![conto](https://github.com/user-attachments/assets/f82662af-4d74-4bd7-9a86-02a25149b83c)

BTW I want to use for something like that in my archiver
😄

**Comment by codewithnick** [comment]
okay thanks for sharing this , can you open a pr adding any copyleft license?

**Comment by codewithnick** [comment]
`Creative Commons Attribution 4.0 International License (CC BY 4.0)

You are free to:
- Share — copy and redistribute the material in any medium or format
- Adapt — remix, transform, and build upon the material for any purpose, even commercially.

Under the following terms:
- Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
`

i think this will be appropriate here

**Comment by fcorbelli** [comment]
Then insert a LICENSE file, and that's all
Thank you

**Comment by fcorbelli** [comment]
CC0-1.0 license is not allowed in Fedora (!), because Fedora requires that all code have a license that guarantees the ability to distribute modifications (which CC0 does not explicitly do for source code).

Can you please change to another one?


https://github.com/fcorbelli/zpaqfranz/issues/133

**Comment by codewithnick** [comment]
Hi @fcorbelli can you please suggest an alternative
this is what the license meant in short id still like to keep the attribution part if possible
```
You are free to:
- Share — copy and redistribute the material in any medium or format
- Adapt — remix, transform, and build upon the material for any purpose, even commercially.

Under the following terms:
- Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
```

**Comment by codewithnick** [comment]
Hi @fcorbelli I changed the LICENSE to MIT LICENSE ,I hope that this will help, If there is still a problem I am open to suggestions

**Comment by codewithnick** [comment]
@ppisar

**Comment by fcorbelli** [comment]
Thank you very much!
