### ISSUE TITLE
Documentation: clearify small letters in <block> font

### ISSUE THREAD

**Issue by codewithnick** [codewithnick/ascii-art#1128]
Some fonts like block do not have small letters
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/ef6a12cb-c4e7-45fa-9035-dcc8b7ef6abb">
this should be clearified in the .md file of that font

change needed in : Fonts/block/block.md

**Comment by sarthaknimbalkar** [comment]
Heyyy @codewithnick 👋,
I would like to help with this issue
