### ISSUE TITLE
Add new font: <c> in straight

### ISSUE THREAD

**Issue by vishallmaurya** [codewithnick/ascii-art#115]
add to #115

**Comment by RajdeepDey010** [comment]
hi @vishallmaurya , I find this problem to be in a kind of uncomfort/untouch zone of my skills.
Can I work on it to explore the things to learn here?
thankyou!

**Comment by sachinkumar911** [comment]
@RajdeepDey010  you should create a new issue then we will assing you..

**Comment by AnshumanMahato** [comment]
Okk @vishallmaurya  go ahead
