### ISSUE TITLE
Add character: V to font: Block

### ISSUE THREAD

**Issue by Fictionistique** [codewithnick/ascii-art#1196]
*Character* : V
*Font* : block

**Comment by Fictionistique** [comment]
@ASCII_BOT claim

**Comment by Fictionistique** [comment]
@ASCII_BOT claim

**Comment by Varun-Kolanu** [comment]
@ASCII_BOT claim

**Comment by Varun-Kolanu** [comment]
@ASCII_BOT claim

**Comment by Varun-Kolanu** [comment]
@ASCII_BOT abandon

**Comment by Varun-Kolanu** [comment]
> @ASCII_BOT claim

There was a bug of Uppercase names in the bot, which got fixed now. You can claim yourself by again claiming

**Comment by Fictionistique** [comment]
@ASCII_BOT claim
Thank you.
