### ISSUE TITLE
Add previews for Carlos font

### ISSUE THREAD

**Issue by AnshumanMahato** [codewithnick/ascii-art#130]
You need to add the previews for each alphabet(both uppercase and lowercase) and numbers.

You will find the link to the font in respective markdown file.

**Comment by AlexWeb07** [comment]
I will do it sir.... If possible then please assign it me

**Comment by AlexWeb07** [comment]
I can add the previews of each uppercase alphabet and numbers for the carlos font

**Comment by AlexWeb07** [comment]
Please assign to me sir ... its a humble request

**Comment by AlexWeb07** [comment]
Thanks
