### ISSUE TITLE
want to add all the numbers to boomer font

### ISSUE THREAD

**Issue by AlexWeb07** [codewithnick/ascii-art#142]

**Comment by AnshumanMahato** [comment]
code or readme?

**Comment by AlexWeb07** [comment]
I want to add all the numbers in banner font (code+readme).

There was a mistake done by me while typing the font name. I
sincerely apologize for that.

**Comment by AnshumanMahato** [comment]
I already assigned that issue to you #133 . you may add the code under that as well... I'm closing this as duplicate

**Comment by AlexWeb07** [comment]
Ok, thanks.
