### ISSUE TITLE
Use Enums for names of fonts

### ISSUE THREAD

**Issue by PranjalKhatri** [codewithnick/ascii-art#143]
It will be easier as it will show in intellisence also

**Comment by PranjalKhatri** [comment]
I am doing it

**Comment by AnshumanMahato** [comment]
good idea... go ahead. 👍👍

**Comment by PranjalKhatri** [comment]
I am very interested in this project and want to contribute to the project
but not compeletely beginner level , can I clone this repository and
further develop it? I will not remove the contributors page and will
mention the link to the original repo , just wanted to develop it at a
faster pace . Is it okay with you?
