### ISSUE TITLE
Programme to generate program for font array

### ISSUE THREAD

**Issue by PranjalKhatri** [codewithnick/ascii-art#151]
A c++  program in which we can paste the asci code from website and it will generate the character array code for it. Assign it to me
It will solve all the font adding hustle.

**Comment by AnshumanMahato** [comment]
Well, this project was started so that even beginners could contribute. Hence the slightly repetitive nature of this project.

I understand your proposition, but unfortunately, it goes against the purpose of this project. So I cannot approve. 

Anyways, thanks for the consideration.😊
