### ISSUE TITLE
Add character: z to font: boomer

### ISSUE THREAD

**Issue by prajjawal007** [codewithnick/ascii-art#160]
*Character* : z
*Font* : boomer

**Comment by AnshumanMahato** [comment]
As you are working on a lowercase alphabet, make sure it aligns well

issues like this should be taken care of

![image](https://github.com/codewithnick/ascii-art/assets/58422570/37014ef1-92fa-4f41-a6f1-9646dbf5df2a)

**Comment by prajjawal007** [comment]
> As you are working on a lowercase alphabet, make sure it aligns well
> 
> issues like this should be taken care of
> 
> ![image](https://user-images.githubusercontent.com/58422570/272658554-37014ef1-92fa-4f41-a6f1-9646dbf5df2a.png)

I have taken care of it.
<img width="127" alt="image" src="https://github.com/codewithnick/ascii-art/assets/144593090/0629b33e-d9e1-42aa-8285-f2ac9d9ea271">
