### ISSUE TITLE
Add new font : I <STARWAR>

### ISSUE THREAD

**Issue by gulshankapse** [codewithnick/ascii-art#222]
I can code for font I in starwar

**Comment by Harishprethiv7** [comment]
I can do it.
Kindly assign it to me.

**Comment by RAGHAVS1304** [comment]
@codewithnick i can do this please assign this issue to me

**Comment by AnshumanMahato** [comment]
@Harishprethiv7 and @RAGHAVS1304, check the font files for missing characters. Then, check for any existing opened issues for that character. If no issues exist, open a new issue specifying the character and the font. I will assign that to you. 😊

**Comment by RAGHAVS1304** [comment]
I want to add character I in font Carlos.Please assign it to me
