### ISSUE TITLE
Add character: a to font: carlos

### ISSUE THREAD

**Issue by RAGHAVS1304** [codewithnick/ascii-art#223]
*Character* : a
*Font* : carlos

**Comment by AnshumanMahato** [comment]
cool... go ahead @RAGHAVS1304

**Comment by RAGHAVS1304** [comment]
@AnshumanMahato i tried this issue to my best potential, but unfortunately even after that, i was unable to solve it.
Please unassign it from me.
Sorry for that.
Thanks
