### ISSUE TITLE
Add character: <X> to font: <carlos>

### ISSUE THREAD

**Issue by amitkr7893** [codewithnick/ascii-art#225]
*Character* : <X>
*Font* : <Carlos>

**Comment by amitkr7893** [comment]
#225 "code for X is added"

![Capture](https://github.com/codewithnick/ascii-art/assets/144598944/ae26ce02-032b-4041-b1ac-e4c659bb4c80)

**Comment by AnshumanMahato** [comment]
Hey @amitkr7893, don't close issues yourself. Just link it to the PR with something like `closes` or 'resolves`; GitHub will handle the rest. It is not a big deal, but helps us keep track in case the PR is not merged for some reason.

**Comment by amitkr7893** [comment]
It was a mistake, what should I do next ?

**Comment by AnshumanMahato** [comment]
Don't worry you dont need to do anything now. Just take care from next time. 😊
