### ISSUE TITLE
Add character: <F> to font: <Carlos>

### ISSUE THREAD

**Issue by Bhaveshgupta00** [codewithnick/ascii-art#228]
*Character* : <F>
*Font* : <Carlos>

**Comment by AdityaDhavale** [comment]
@Bhaveshgupta00 
I would like to work on this issue , please assign me

**Comment by AnshumanMahato** [comment]
@AdityaDhavale check the font files for missing characters. Then, check for any existing opened issues for that character. If no issues exist, open a new issue specifying the character and the font. I will assign that to you. 😊

**Comment by sachinkumar911** [comment]
@Bhaveshgupta00  are you working on it??

**Comment by rishavr920** [comment]
assign me i can do it

**Comment by sachinkumar911** [comment]
@rishavr920  i am assigning it to you..

**Comment by AnshumanMahato** [comment]
@Yordaniss, would you like to work on this?

**Comment by Yordaniss** [comment]
> @Yordaniss, would you like to work on this?

@AnshumanMahato  yes, sure 🙂

**Comment by Yordaniss** [comment]
@AnshumanMahato work is done. Please review the changes 🙂

**Comment by AnshumanMahato** [comment]
@Yordaniss, everything works as intended. 😊
