### ISSUE TITLE
Add character: <G> to font: <banner>

### ISSUE THREAD

**Issue by akashKumar06** [codewithnick/ascii-art#236]
*Character* : <G>
*Font* : <b
![Screenshot (62)](https://github.com/codewithnick/ascii-art/assets/117292434/2fe6c8ae-f740-4914-a21b-b75efddd09e0)
anner>

**Comment by keshav278** [comment]
Hi, may I be assigned this issue?

**Comment by AnshumanMahato** [comment]
@keshav278 check the font files for missing characters. Then, check for any existing opened issues for that character. If no issues exist, open a new issue specifying the character and the font. I will assign that to you. 😊
