### ISSUE TITLE
Add character: <u> to font: <straight>

### ISSUE THREAD

**Issue by amitkr7893** [codewithnick/ascii-art#261]
*Character* : <x>
*Font* : <straight>

**Comment by vivekmahindrakar** [comment]
@amitkr7893 ✌
could you please elaborate the issue?

**Comment by AnshumanMahato** [comment]
Our project has different fonts that print characters in a specific style style. You can find these fonts in the `Fonts` directory. Each font has two files - a header file and a markdown file. A preview for each character is present in the associated markdown file. You refer to that when defining the function for the character you want to add.

You define the function in the associated Header file. For Starwar font, that would be the `starwar.h` file. We have already provided the body for all functions in the comments. All you need to do is uncomment that and make the necessary changes.

https://github.com/codewithnick/ascii-art/blob/73d9e32ed592909625de99c46e812baadaf16025/Fonts/starwar/starwar.h#L140-L149

Now, each character is a 2D grid. The rows and columns for the grid depend upon the specific font. For starwar, we have '6' rows and '13' columns. All you need to do is fill this grid according to the preview.

https://github.com/codewithnick/ascii-art/blob/73d9e32ed592909625de99c46e812baadaf16025/Fonts/starwar/starwar.md?plain=1#L86-L92

For testing, you use the `example.cpp` file. Here, specify the font you're working on. Then, print your character to see if it prints correctly.

https://github.com/codewithnick/ascii-art/blob/73d9e32ed592909625de99c46e812baadaf16025/example.cpp#L1-L11

You need to check the font files for missing characters. Then, check for any existing opened issues for that character. If no issues exist, open a new issue specifying the character and the font. I will assign that to you. 😊

@vivekmahindrakar , I hope this helped. If there is anything else you need, feel free to ask. 😊
