### ISSUE TITLE
Can add Letter - B in starwar

### ISSUE THREAD

**Issue by vishallmaurya** [codewithnick/ascii-art#30]
added to me

**Comment by vishallmaurya** [comment]
add to #30

**Comment by AnshumanMahato** [comment]
@vishallmaurya code or readme?

**Comment by vishallmaurya** [comment]
@AnshumanMahato sir code

**Comment by AnshumanMahato** [comment]
well, the class has not been initialized for this font. So you need to wait for that as someone else is working on that currently. But in the meantime... you may open up an issue to add character previews to the respective MD files.
