### ISSUE TITLE
Add character: <p> to font: <straight>

### ISSUE THREAD

**Issue by XARTAN21** [codewithnick/ascii-art#330]
*Character* : <p>
*Font* : <straight>

**Comment by DanielZhang111** [comment]
Can I get some more information on this and get assigned?

**Comment by AnshumanMahato** [comment]
@DanielZhang111, See here to understand what needs to be done.
https://github.com/codewithnick/ascii-art/issues/261#issuecomment-1751997816

**Comment by DanielZhang111** [comment]
So is it possible for me to still do it for it to count for Hacktoberfest or not? Seems like it is completed
