### ISSUE TITLE
Add character: <3> to font: <STARWAR>

### ISSUE THREAD

**Issue by ankitkujur15** [codewithnick/ascii-art#340]
*Character* : <character> 3
*Font* : <fontname> starwar

**Comment by Manas-Pathak** [comment]
I can work on this issue @AnshumanMahato

**Comment by AnshumanMahato** [comment]
Go ahead

**Comment by Manas-Pathak** [comment]
@AnshumanMahato I have checked, corrected <3> is already in <STARWAR>
