### ISSUE TITLE
Add character: 0 to font: starwar

### ISSUE THREAD

**Issue by NANDANA-S-P** [codewithnick/ascii-art#359]
*Character* : 0
*Font* : starwar

**Comment by NANDANA-S-P** [comment]
Can u assign me?

**Comment by Taofeeqah** [comment]
Can the issue be assigned to me?

**Comment by AnshumanMahato** [comment]
@Taofeeqah look for missing characters in any of the fonts. If there is no active issue for it, open an issue and I will assign that to you. 😊
