### ISSUE TITLE
Add character: <Z> to font: <starwar>

### ISSUE THREAD

**Issue by NeerajSh-16** [codewithnick/ascii-art#363]
*Character* : <character>
*Font* : <fontname>

**Comment by y-ashaswini** [comment]
Please assign this to me!

**Comment by AnshumanMahato** [comment]
Hey @NeerajSh-16, I am giving this one to @y-ashaswini

**Comment by AnshumanMahato** [comment]
@y-ashaswini you may work on it. 👍

**Comment by NeerajSh-16** [comment]
@AnshumanMahato , sure sir.

**Comment by AnshumanMahato** [comment]
assigned in #894
