### ISSUE TITLE
Add character: <M> to font: <Straight>

### ISSUE THREAD

**Issue by vishalmishraa** [codewithnick/ascii-art#376]
want to add M to Straight

**Comment by DanielZhang111** [comment]
Can i get assigned? And given some more information?

**Comment by vishalmishraa** [comment]
> Can i get assigned? And given some more information?

Can you search for other characters..coz i already created PR .

**Comment by DanielZhang111** [comment]
What is PR?

**Comment by DanielZhang111** [comment]
Do I just add a different letter?

**Comment by vishalmishraa** [comment]
> Do I just add a different letter?

yup search other letter which are not assigned to anyone .

**Comment by DanielZhang111** [comment]
ok
