### ISSUE TITLE
Add new font: <c> in lowercase banner font

### ISSUE THREAD

**Issue by alucard017** [codewithnick/ascii-art#386]
Add lowercase font 'c' in banner.h

**Comment by alucard017** [comment]
Kindly assign me this issue..

**Comment by alucard017** [comment]
@AnshumanMahato Sir, the description of banner font is absent in Readme.md file.
You can raise an issue regarding that. Also kindly assign me the issue for working with lowercase letters so that the dynamic character grid will come to play his role..

**Comment by AnshumanMahato** [comment]
@alucard017 add all the small case previews to the md file. but implement the function only for c. Rest all will be added as and when issues are raised.

**Comment by AnshumanMahato** [comment]
by the way, the small case ones may look similar to uppercase but have a small grid size. so take note of that
you will find the previews here https://ascii-generator.site/t/

**Comment by alucard017** [comment]
small case previews are already there in the md file. Letters are utilizing lower grid size than the uppercase ones.
