### ISSUE TITLE
Adjust boomer font to use dynamic character grid

### ISSUE THREAD

**Issue by AnshumanMahato** [codewithnick/ascii-art#390]
Step 1 -> Take a look at the code for established character functions.
Step 2 -> Identify the actual no. of rows and columns used.
Step 3 -> Pass it to the associated `char **getCharGrid` method.

**Comment by vishalmishraa** [comment]
Assign this to me.

**Comment by gaurav12devloper** [comment]
kindly assign to me

**Comment by AnshumanMahato** [comment]
ok @gaurav12devloper go ahead
