### ISSUE TITLE
Adjust banner font to use dynamic character grid

### ISSUE THREAD

**Issue by AnshumanMahato** [codewithnick/ascii-art#393]
Step 1 -> Take a look at the code for established character functions.
Step 2 -> Identify the actual no. of rows and columns used.
Step 3 -> Pass it to the associated `char **getCharGrid` method.

**Comment by alucard017** [comment]
assign me this issue..

**Comment by alucard017** [comment]
@AnshumanMahato Sir, 
I have already submitted a PR, kindly check it.

**Comment by AnshumanMahato** [comment]
@alucard017 I added a comment, kindly check it 😁

**Comment by alucard017** [comment]
@AnshumanMahato  I have added a comment regarding the issue, Sir check it.
