### ISSUE TITLE
Add character: <P> to font: <straight>

### ISSUE THREAD

**Issue by gaurav12devloper** [codewithnick/ascii-art#408]
*Character* : <character>
*Font* : <fontname>

**Comment by DanielZhang111** [comment]
Can I get assigned?

**Comment by AnshumanMahato** [comment]
@gaurav12devloper I am giving this to @DanielZhang111. @DanielZhang111 For further contributions, look for missing characters in any fonts. If there is no open issue for that, then open an issue and I will assign that to you 😊

**Comment by DanielZhang111** [comment]
Thanks! I will work on it later!

**Comment by DanielZhang111** [comment]
I'm kind of confused on how to do this, could I get some tips?

**Comment by im0vishal** [comment]
@sachinkumar911 please assign me this..

**Comment by AnshumanMahato** [comment]
assigned in #978
