### ISSUE TITLE
Add new font: <block>

### ISSUE THREAD

**Issue by NeerajSh-16** [codewithnick/ascii-art#440]

**Comment by AnshumanMahato** [comment]
woah nice... describe it a bit

**Comment by NeerajSh-16** [comment]
![Screenshot (10047)](https://github.com/codewithnick/ascii-art/assets/144585755/707c1518-ae9f-457f-8e85-bc0f6196fe8e)
![Screenshot (10048)](https://github.com/codewithnick/ascii-art/assets/144585755/a58002d8-60c6-46c5-8781-be48b3152c15)

It looks like this and it only Upper Case letters.
I've completed its .md file .
Sir, do I've also to create '.h' file with some starter code in it along with its '.md' file ?

**Comment by AnshumanMahato** [comment]
Cool. Make a PR. I'll take a look into it later today

**Comment by AnshumanMahato** [comment]
Wait for any open PR to merge before starting a new one.

**Comment by NeerajSh-16** [comment]
Ok sir.
