### ISSUE TITLE
Add character: <w> to font: <boomer>

### ISSUE THREAD

**Issue by Harsh-00** [codewithnick/ascii-art#528]
*Character* : <w>
*Font* : <boomer>

**Comment by Harsh-00** [comment]
Hello, I'm interested in working on this issue. Could you please assign it to me?

**Comment by AnshumanMahato** [comment]
sure go ahead

**Comment by AnshumanMahato** [comment]
unassigned due to inactivity

**Comment by rishavr920** [comment]
sir assign to me i will do it

**Comment by pronajit** [comment]
Assign to me sir

**Comment by pronajit** [comment]
@AnshumanMahato sir please assign this to me

**Comment by AnshumanMahato** [comment]
@rishavr920 I am assigning this in #1019. @pronajit as you have opened a vast no. of Issues, I'll assign you from there
