### ISSUE TITLE
Add character: <q> to font: <Boomer>

### ISSUE THREAD

**Issue by IshitaPathak** [codewithnick/ascii-art#559]
*Character* : q
*Font* : Boomer

**Comment by ayush4028** [comment]
Hey @IshitaPathak, I think that I can do this task. can you please assign me this task ?

**Comment by IshitaPathak** [comment]
Hey @ayush4028 . I am not the maintainer of this project
Closing this issue.As I have checked this issue is already created

**Comment by AnshumanMahato** [comment]
@IshitaPathak I am assigning this to you.
@ayush4028 look for some other missing character in any of the fonts. If there is no active issue for it, open one and I will assign that to you.

**Comment by IshitaPathak** [comment]
@AnshumanMahato I have created a PR #563 for this issue please take a look and lemme know if any modification need to be done.
