### ISSUE TITLE
Add character: <6> to font: <carlos>

### ISSUE THREAD

**Issue by Harry121199** [codewithnick/ascii-art#600]
*Character* : <character>
*Font* : <fontname>

**Comment by AidenW8512** [comment]
what file is this for?

**Comment by AnshumanMahato** [comment]
unassigned as inactive

**Comment by im0vishal** [comment]
Character : 6
Font : carlos

**Comment by im0vishal** [comment]
Assign me this

**Comment by sachinkumar911** [comment]
@im0vishal  i am assigning it to you .
