### ISSUE TITLE
Add character: <m> to font: <banner>

### ISSUE THREAD

**Issue by abhay5624** [codewithnick/ascii-art#608]
*Character* : m
*Font* : banner

**Comment by AnshumanMahato** [comment]
make sure that it aligns properly
this should not be happening
<img width="126" alt="Screenshot 2023-10-04 171420" src="https://github.com/codewithnick/ascii-art/assets/58422570/eced340b-c72b-46be-87dd-34694cb33582">

the trick is to to take some extra rows and keep the top rows empty.😊
