### ISSUE TITLE
Font : Boomer ; Letter : r

### ISSUE THREAD

**Issue by pronajit** [codewithnick/ascii-art#64]
I want to write code for letter r

**Comment by AnshumanMahato** [comment]
@pronajit you working on this?

**Comment by pronajit** [comment]
yes

**Comment by Manas-Pathak** [comment]
@AnshumanMahato please assign me this issue

**Comment by AnshumanMahato** [comment]
ok @Manas-Pathak, go ahead, As it is a small case character, make sure it aligns with the bottom. This must not happen.
<img width="127" alt="Screenshot 2023-10-27 195652" src="https://github.com/codewithnick/ascii-art/assets/58422570/4be082b8-4579-49fd-bbc8-fe2d09b6d29d">

**Comment by Manas-Pathak** [comment]
@AnshumanMahato added the  code for the lowercase letter r. And it aligns with the bottom too.
