### ISSUE TITLE
Add character: <S> to font: <STARWAR>

### ISSUE THREAD

**Issue by nk12nidhi12** [codewithnick/ascii-art#650]
*Character* : <S>
*Font* : <STARWAR>

**Comment by pronajit** [comment]
sir assign to me i will do it

**Comment by pronajit** [comment]
@AnshumanMahato sir please assigned it to me

**Comment by AnshumanMahato** [comment]
@pronajit you can work on this

**Comment by pronajit** [comment]
ok sir

**Comment by zpotthoff** [comment]
Hi, I see this hasn't been worked on in a while. I'm happy to submit a PR for it.

**Comment by zpotthoff** [comment]
PR: https://github.com/codewithnick/ascii-art/pull/1156
