### ISSUE TITLE
Add character: <S> to font: <amongus>

### ISSUE THREAD

**Issue by moniiccaaa** [codewithnick/ascii-art#722]
*Character* : S
*Font* : amongus

**Comment by Yordaniss** [comment]
Hey @moniiccaaa I would like to work on this issue. Can you please assign this to me? 🙂

**Comment by AnshumanMahato** [comment]
@moniiccaaa I am giving this one to @Yordaniss

**Comment by Yordaniss** [comment]
@AnshumanMahato thanks a lot 🙂

**Comment by Yordaniss** [comment]
@AnshumanMahato work is done, please review my changes 🙂
