### ISSUE TITLE
Add character: <Z> to font: <Block>

### ISSUE THREAD

**Issue by PRIYANSHU210021** [codewithnick/ascii-art#735]
*Character* : <character>
*Font* : <fontname>

**Comment by abhinavs1920** [comment]
I am working on it

**Comment by AnshumanMahato** [comment]
@abhinavs1920  Look for any missing characters in any of the fonts. If there are no existing issues, open an issue for that and I'll assign that to you.

**Comment by AnshumanMahato** [comment]
@PRIYANSHU210021 you can work on it.
