### ISSUE TITLE
Update readme with new fonts information 

### ISSUE THREAD

**Issue by codewithnick** [codewithnick/ascii-art#836]
New fonts have been added in code but not updated in readme.md

**Comment by jaivardhan-bhola** [comment]
Can I work on this?

**Comment by jaivardhan-bhola** [comment]
Can I work on this?

**Comment by AnshumanMahato** [comment]
@jaivardhan-bhola sure you can

**Comment by jaivardhan-bhola** [comment]
Can I get some details

**Comment by AnshumanMahato** [comment]
@jaivardhan-bhola sure. 

The main readme files contain links to Readme files of individual fonts
<img width="172" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/52fd2699-e2f0-4ed3-81e5-a4da1352bf2e">

Some new fonts have been added during Hacktoberfest. You need to link them as well.

The readme files for the fonts are in their respective folders which are inside the Fonts directory.
