### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by jlewismith** [codewithnick/ascii-art#867]
I haven't been able to find a license for this repository. Is there a way for us to add one? That would facilitate people legally being able to use this project. 

More information here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by AnshumanMahato** [comment]
Exactly. A license is important for any open-source project. But we haven't had any discussions about the license yet. Probably, it will be added after the hacktoberfest. So, until then, I'm closing this issue.
