### ISSUE TITLE
Add character: <3> to font: <amongus>

### ISSUE THREAD

**Issue by Kranti-Kumar** [codewithnick/ascii-art#878]
*Character* :  3
*Font* : amongus

**Comment by Kranti-Kumar** [comment]
sir this is my first issue please assign it to me

**Comment by AnshumanMahato** [comment]
hey @Kranti-Kumar you can also look into old issues with the 'up-for-grab' tag. That would help us clear old issues. Just comment in any of those if you want to work on them.
